---
  - name: downloadfile
    hosts: localhost
    vars:
      controller_host: 192.168.133.236
      
    collections:
      - awx.awx
    tasks:
      - name: Launch a job
        job_launch:
          job_template: downloadfile	
          validate_certs: no
          controller_username: admin
          controller_password: redhat
          controller_host: 192.168.133.236
        register: job

      - name: Wait for job max 120s
        job_wait:
          job_id: "{{ job.id }}"
          timeout: 120
          validate_certs: no
          controller_username: admin
          controller_password: redhat
          controller_host: 192.168.133.236
